package org.richfaces.cdk.model;


/**
 * <p class="changed_added_4_0">
 * This Interface describes all JSF objects that can be generated by cdk:
 * </p>
 * <ul>
 * <li>{@link jakarta.faces.component.UIComponent}</li>
 * <li>{@link jakarta.faces.render.Renderer}</li>
 * <li>{@link jakarta.faces.convert.Converter}</li>
 * <li>{@link jakarta.faces.validator.Validator}</li>
 * <li>{@link jakarta.faces.component.behavior.ClientBehavior}</li>
 * <li>{@link jakarta.faces.render.ClientBehaviorRenderer}
 * </ul>
 *
 * @author asmirnov@exadel.com
 *
 */
public interface GeneratedFacesComponent extends FacesComponent {
    /**
     * <p class="changed_added_4_0">
     * </p>
     *
     * @return the baseClass
     */
    ClassName getBaseClass();

    /**
     * <p class="changed_added_4_0">
     * </p>
     *
     * @param baseClass
     */
    void setBaseClass(ClassName baseClass);

    /**
     * <p class="changed_added_4_0">
     * </p>
     *
     * @return
     */
    Boolean getGenerate();

    /**
     * <p class="changed_added_4_0">
     * </p>
     *
     * @param generate
     */
    void setGenerate(Boolean generate);
}